import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import { generateSeriesBibleHtml } from './seriesBible'
import { applyWatermark } from './watermark'

function slugify(str) {
  return String(str).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

async function blobFromUrl(url) {
  try {
    const res = await fetch(url)
    return await res.blob()
  } catch (_) {
    return null
  }
}

// Returns a blob for a (possibly watermarked) image URL.
// applyWatermark already no-ops (returns original url) for paid plans, so no
// separate shouldWatermark guard is needed here.
// The Promise.race with an 8 s timeout ensures a stalled watermark never
// freezes the ZIP export — it falls back to the original url.
async function imageBlobForExport(url, plan) {
  const watermarkedUrl = await Promise.race([
    applyWatermark(url, 'BookFilm Studio', plan),
    new Promise((r) => setTimeout(() => r(url), 8000)),
  ])
  const blob = await blobFromUrl(watermarkedUrl)
  // Revoke the temporary object URL created by applyWatermark (if any)
  if (watermarkedUrl !== url) URL.revokeObjectURL(watermarkedUrl)
  return blob
}

export async function exportZip(series, mediaState = {}, onProgress, plan = 'free') {
  const zip = new JSZip()
  const root = zip.folder(slugify(series.title))
  let done = 0
  const tasks = []

  // Series bible HTML
  root.file('series-bible.html', generateSeriesBibleHtml(series, mediaState))

  // AI-generated content disclosure manifest
  root.file('AI-DISCLOSURE.txt', [
    `BookFilm Studio — AI-Generated Content Disclosure`,
    `=================================================`,
    ``,
    `All images, video clips, and voice-overs in this ZIP archive are`,
    `AI-synthesised outputs produced by third-party AI providers (Replicate,`,
    `fal.ai, ElevenLabs, OpenAI, etc.).`,
    ``,
    `When publishing or sharing this content you are responsible for:`,
    `  1. Disclosing its AI origin per applicable platform policies`,
    `     (Instagram, TikTok, YouTube, X/Twitter, LinkedIn, etc.).`,
    `  2. Complying with the EU AI Act (Regulation (EU) 2024/1689) if`,
    `     distributing to recipients in the European Union.`,
    `  3. Ensuring you own or have rights to the source text used to`,
    `     generate this package.`,
    ``,
    `Series: ${series.title || 'Untitled'}`,
    `Exported: ${new Date().toISOString()}`,
    ``,
    `Generated by BookFilm Studio — https://bookfilm.studio (placeholder)`,
  ].join('\n'))

  // Characters folder
  const charsFolder = root.folder('characters')
  for (const char of series.characters || []) {
    const asset = mediaState.characters?.[char.id]
    const url = asset?.localUrl || asset?.remoteUrl
    if (url) {
      tasks.push(
        imageBlobForExport(url, plan).then(blob => {
          if (blob) charsFolder.file(`${slugify(char.name)}-portrait.jpg`, blob)
          onProgress?.(++done)
        })
      )
    }
  }

  // Episodes folders
  for (const ep of series.episodes || []) {
    const epFolder = root.folder(`episode-${ep.number}`)

    for (const scene of ep.scenes || []) {
      const key = `ep${ep.number}-s${scene.scene_number}`
      const asset = mediaState.scenes?.[key]
      const url = asset?.localUrl || asset?.remoteUrl
      if (url) {
        tasks.push(
          blobFromUrl(url).then(blob => {
            if (blob) epFolder.file(`scene-${scene.scene_number}.mp4`, blob)
            onProgress?.(++done)
          })
        )
      }

      // Dialogue audio
      for (let dIdx = 0; dIdx < (scene.dialogue || []).length; dIdx++) {
        const dKey = `${key}-d${dIdx}`
        const dAsset = mediaState.dialogue?.[dKey]
        const dUrl = dAsset?.audioUrl
        if (dUrl) {
          tasks.push(
            blobFromUrl(dUrl).then(blob => {
              if (blob) epFolder.file(`scene-${scene.scene_number}-dialogue-${dIdx + 1}.mp3`, blob)
              onProgress?.(++done)
            })
          )
        }
      }
    }
  }

  await Promise.all(tasks)

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } })
  saveAs(blob, `${slugify(series.title)}-cinematic-series.zip`)
}
