// Pluggable candidate scoring for the BookFilm Engine best-of-N ensemble.
//
// scoreCandidate() returns a number in [0,1] expressing how "good" a generated
// MEDIA candidate is. It is the single seam where real quality models plug in:
//   - aesthetic scoring (e.g. a LAION-aesthetic / image-quality model)
//   - identity-match vs characterRef (face/embedding similarity for consistency)
//   - prompt-adherence (CLIP/SigLIP image-text alignment)
// Today it delegates to an external HTTP scoring service when ENGINE_SCORE_URL is
// set, and otherwise returns a deterministic NEUTRAL score so best-of-N never makes
// an arbitrary choice (it falls back to "first candidate wins" on ties).
//
// Dependency-free and fast: a single fetch, base64-encoded bytes, neutral on any error.

import { config } from '../config.js'

const NEUTRAL = 0.5

/**
 * Score one generated candidate.
 *
 * @param {object}  args
 * @param {string}  args.type          generation type ('image' | 'video' | 'voice' | 'music' | 'text')
 * @param {Buffer} [args.buffer]       the generated bytes (media only)
 * @param {string} [args.mimeType]     candidate mime type
 * @param {string} [args.prompt]       the prompt used to generate the candidate
 * @param {string} [args.characterRef] optional character reference (for identity-match scorers)
 * @returns {Promise<number>} score in [0,1]; NEUTRAL (0.5) when no scorer configured or on any error.
 */
export async function scoreCandidate({ type, buffer, mimeType, prompt, characterRef }) {
  const url = config.engine.scoreUrl
  // Inert by default: no scorer configured → neutral, deterministic score.
  if (!url) return NEUTRAL
  // Nothing to score (e.g. text or an empty candidate) → neutral.
  if (!buffer) return NEUTRAL

  try {
    // Transport: JSON with base64-encoded bytes. The scoring service receives
    // { type, prompt, character_ref, mime, data_base64 } and returns { score }.
    const headers = { 'Content-Type': 'application/json' }
    if (config.engine.apiKey) headers.Authorization = `Bearer ${config.engine.apiKey}`

    const res = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        type,
        prompt: prompt || '',
        character_ref: characterRef || null,
        mime: mimeType || 'application/octet-stream',
        data_base64: Buffer.from(buffer).toString('base64'),
      }),
      signal: AbortSignal.timeout(config.engine.timeoutMs || 600000),
    })
    if (!res.ok) return NEUTRAL
    const data = await res.json().catch(() => null)
    const score = Number(data?.score)
    if (!Number.isFinite(score)) return NEUTRAL
    // Clamp into [0,1] so a misbehaving scorer can't distort selection.
    return Math.max(0, Math.min(1, score))
  } catch {
    // Any failure (network, timeout, bad JSON) → neutral, never block the job.
    return NEUTRAL
  }
}
